# Service
apiVersion: v1
kind: Service
metadata:
  name: game-2048-service
  namespace: image
  labels:
    app: game-2048
spec:
  type: NodePort
  selector:
    app: game-2048
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30090
  sessionAffinity: ClientIP
